Map<int, String> weatherDescription = {
  0: 'Clear sky',
  1: 'Mainly clear',
  2: 'partly cloudy',
  3: 'and overcast',
  45: 'Fog',
  48: 'depositing rime fog',
  51: 'Drizzle: Light ',
  53: 'Drizzle: moderate ',
  55: 'Drizzle: dense ',
  56: 'Freezing Drizzle: Light ',
  57: 'Freezing Drizzle: dense ',
  61: 'Rain: Slight',
  63: 'Rain: moderate',
  65: 'Rain: heavy      ',
};
